language: ruby
rvm:
  - 2.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - gem uninstall bundler
  - gem install bundler --version '2.1.4'
  
script:
  - bundle exec jekyll build --drafts
#  - bundle exec htmlproof ./_site

notifications:
  email: false
